[package]
name = "ppo_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
gym-rs = "0.2.1"
tch = "0.9.0"
